### ISSUE TITLE
[Fabric 1.17.1 Chickens v1.0.1] Shift right-clicking a nest on top of a chest from above throws an unhandled exception

### ISSUE THREAD

**Issue by Jvs34** [CrimsonFluff/Crimson-Chickens#13]
What I did to reproduce it is to shift right-click a nest while looking down on a chest.
The one on the left didn't crash as I did it while on the same level as the chest.
![2021-11-29_10 06 35](https://user-images.githubusercontent.com/1412812/143838865-fd50a380-4019-4d54-9f11-8bd8c29965bf.png)

Here's the latest.log, the instance is a 1.17.1 with the Fabric loader at 0.12.5 and Fabric Api 0.4.3, along with REI.
[latest.log](https://github.com/CrimsonFluff/Crimson-Chickens/files/7616872/latest.log)

**Comment by CrimsonFluff** [comment]
Thank you for the detailed report.  I used a wrong method when porting to fabric
its fixed in the next update (1.03 for 1.16.5/1.17.1, and 1.0.1 for 1.18)

Thank you
