### ISSUE TITLE
[Fabric 1.17.1 Chickens v1.0.3] Animal Capture Net can capture animals while it's full, deleting the old animal.

### ISSUE THREAD

**Issue by Jvs34** [CrimsonFluff/Crimson-Chickens#14]
Sorry to make another issue so soon but this one is less game breaking at least.

As said in the title, the animal capture net can continue capturing animals, overriding the old one without warning.
I found out when I miss clicked another animal instead of the block below it, deleting my other chicken.
No useful info on the logs this time but I've got a video instead.

https://www.youtube.com/watch?v=F8lUbHgzmW8

The instance is still the same, 1.17.1 with the Fabric loader at 0.12.5 and Fabric Api 0.4.3, along with REI.

**Comment by CrimsonFluff** [comment]
Testing is all good, errors are welcome, but they're not if you get what I mean, lol

At a quick look it appears I have absolutely no code to protect against a full animal net. All the way back to the forge versions too

*should* be done in the next update

Thanks

**Comment by CrimsonFluff** [comment]
and before you mention it, you cant capture Llamas in the Net. Some weird vanilla interaction  :-)
