### ISSUE TITLE
Cacti chicken crash

### ISSUE THREAD

**Issue by BernardoGrigiastro** [CrimsonFluff/Crimson-Chickens#15]
Fabric 1.18

Go to a desert and poof, crash to the desktop. Repeatable

I forced rc4 so if thats the prob ignore this :D

https://pastebin.com/Z0QqZqrY

**Comment by CrimsonFluff** [comment]
I spawned a new world and teleported to a desert biome and all was ok?

can you try with 1.18 rc3?

**Comment by BernardoGrigiastro** [comment]
Same crash

**Comment by CrimsonFluff** [comment]
any chance you can zip me your world?

**Comment by BernardoGrigiastro** [comment]
maybe, how?

**Comment by CrimsonFluff** [comment]
ok ignore that - ive found the issue, trying a fix now

**Comment by CrimsonFluff** [comment]
here try this
it happens when a cactus chicken touches another cactus chicken - it goes into an infinite damage loop

https://1drv.ms/u/s!ArSGAcC04KWsyw2hf6NRC5PnwEpI?e=BWfkWd

**Comment by BernardoGrigiastro** [comment]
wow that is very specific! how did you find that out?

Fixed on both rc3 and rc4

Thank you!

ps. do i close it or you do?

**Comment by CrimsonFluff** [comment]
it gave line 515 which is inside the code that controls when the chicken takes damage
it mentions cactus chicken

so I just set up a series of tests to damage a cactus chicken to see if I could make it fail

Ive also made Cactus chickens immune to Cactus damage (in next update), makes sense as nether chickens (like lava/netherite/quartz) are immune to fire

thanks again for the report ;-)

either one of us can close the issue

**Comment by BernardoGrigiastro** [comment]
oh, nice :-)
