### ISSUE TITLE
Not a bug but an opinion..

### ISSUE THREAD

**Issue by BernardoGrigiastro** [CrimsonFluff/Crimson-Chickens#16]
bad title but anyways... i think ducks are too loud specially when far from them

**Comment by CrimsonFluff** [comment]
thats a fairly easy fix.  I had to make do with little sounds I could find on the internet

i'll save that for the next update ;-)

**Comment by BernardoGrigiastro** [comment]
:-D

**Comment by CrimsonFluff** [comment]
I mean I do test code that I change, but I don't actually have people to test the mods properly, in the real-world, if you like  lol

its always best to say "untested", then when the mod breaks its not so disappointing to me or the user  😉

**Comment by CrimsonFluff** [comment]
i'll reduce the sound, someday, sometime
