### ISSUE TITLE
Flint chicken locations

### ISSUE THREAD

**Issue by BernardoGrigiastro** [CrimsonFluff/Crimson-Chickens#18]
I can't find them, not sure why, but none of the whitelisted biomes are options on locatebiome command, I found a Stony Shore through that command but no Flint chickens there, lots of sand chickens though.

**Comment by CrimsonFluff** [comment]
Probably mojang changed the biome names.  I'll look into it

**Comment by BernardoGrigiastro** [comment]
Either i'm really dumb or theres something wrong :) I'm in Windwept Gravelly Hills which is one of the only two Hills and there are Log and Regular chickens, no Flint,.... and Ducks hahaha they are everywhere but you know that already :-D

**Comment by CrimsonFluff** [comment]
did you change the whitelist for flint chickens to spawn in "Windswept Gravelly Hills" or left as default?

cos some biomes have indeed been renamed, which I didnt account for

**Comment by BernardoGrigiastro** [comment]
I left at default, as there are no mountains on the locatebiome options and/or i dont understand that command well, i tried going to the mountains related options to check.

"kill to force" after changing to "Windswept Gravelly Hills" ofc, right?

do you know which biomes flint will be after mojang changes? is this windswept one of them? i want to be in sync with at least for now otherwise my testing is somewhat invalid

**Comment by CrimsonFluff** [comment]
either google the biome name changes, or I will manually go thru the biome list and choose where I think they should spawn

**Comment by BernardoGrigiastro** [comment]
right, just checked and "Windswept Gravelly Hills" is the new "Gravelly Mountains" name :D

**Comment by CrimsonFluff** [comment]
to use it you'll need the actual registry name:

`   public static final ResourceKey<Biome> WINDSWEPT_HILLS = register("windswept_hills");`
   
`   public static final ResourceKey<Biome> WINDSWEPT_GRAVELLY_HILLS = register("windswept_gravelly_hills");`
   
`   public static final ResourceKey<Biome> WINDSWEPT_FOREST = register("windswept_forest");`
   
 `  public static final ResourceKey<Biome> WINDSWEPT_SAVANNA = register("windswept_savanna");  `

**Comment by BernardoGrigiastro** [comment]
yeah i know, those four are your choices for flint?

**Comment by CrimsonFluff** [comment]
no I was just giving an example - I need to have a better look - its nearly 2am and im trying to fix some of my other mods

**Comment by BernardoGrigiastro** [comment]
oh, right, yeah nearly 3am here haha

**Comment by CrimsonFluff** [comment]
So I've changed some of the biomes around for all the chicken configs
After a fair amount of testing I have determined that the chickens spawn anywhere they want to
According to the debug log, the chickens are registered to their correct biomes
I have also halved the number of spawns for all chickens
normal chickens spawn 1-2, instead of 4-4
other chickens spawn 1-2, instead of 1-4

**Comment by BernardoGrigiastro** [comment]
I'm lost... chickens "spawn anywhere they want" OR "are registered to their correct biomes"?
Normal means the "vanilla" one? and "other" means all the others?
what 4-4 and 1-4 means?

**Comment by CrimsonFluff** [comment]
they register to the correct biomes
but in game they seem to appear anywhere. eg: ive had sand chickens in the middle of a river, next to a desert, when the spawn is set to desert

1-4 would be minimum of 1, maximum of 4
vanilla chickens are set to always spawn in groups of 4, hence 4-4

**Comment by BernardoGrigiastro** [comment]
oh, thx for the explanation, yeah sand chickens are almost like the ducks, they are everywhere hahaha

**Comment by CrimsonFluff** [comment]
changed biomes to support name changes in 1.18
