### ISSUE TITLE
AE2 item id change

### ISSUE THREAD

**Issue by BernardoGrigiastro** [CrimsonFluff/Crimson-Chickens#19]
1.18 ae2 changed items id so its chickens need fixing...

"dropItem": "appliedenergistics2:certus_quartz_crystal" >> "dropItem": "ae2:certus_quartz_crystal"
"dropItem": "appliedenergistics2:charged_certus_quartz_crystal" >> "dropItem": "ae2:charged_certus_quartz_crystal"

i would do a pr but i'm not confident enough working with git yet

**Comment by CrimsonFluff** [comment]
so fork the project
use the github app to clone your fork to your pc
change the config file
use the github app to push your changes from pc to your github
then click contribute
type a reason for the changes
then click something else and i'll receive a PR request

if Im remembering correctly. I do it thru IntelliJ's github plugin. But the github app is easiest way to push changes from your pc to your github repository

**Comment by BernardoGrigiastro** [comment]
I have it forked already and i use intellij but i only used the github plugin (for testing) once and it worked fine i guess...  i dont want to install the app though

Idk, Fabric is only 1.18 version released so far...

> WARNING

> Please note that this release is very unstable since there were massive changes internally from 1.17 to 1.18. Items will not migrate over from 1.17 or before due to the mod-id changing to ae2 in this release, and fully unifying fluid/item machines.

> More in-depth release notes will follow in a later release (probably in the beta).

**Comment by CrimsonFluff** [comment]
then just click the "commit" tab on the top left of intellij
select the changed files
click "Commit and Push"
click "Push anyways"
click "Push" again and boom, it should upload the changes to your github repo

**Comment by BernardoGrigiastro** [comment]
thank you!

**Comment by CrimsonFluff** [comment]
i'll change it
