### ISSUE TITLE
Rei breeding recipes wrong indev version

### ISSUE THREAD

**Issue by BernardoGrigiastro** [CrimsonFluff/Crimson-Chickens#22]
Rei breeding recipes are very wrong indev, i'll give a look at it but i guess its too advanced for me

Another thing prolly related, as you disabled tooltips for Rei integration, the "Spawns naturally" tip is not displaying

**Comment by CrimsonFluff** [comment]
change line 50 in `ReiPlugin.java` to

`                registry.add(new breedDisplay(new breedRecipe(new ItemStack(parentA.spawnEggItem), new ItemStack(parentB.spawnEggItem), new ItemStack(chickenData.spawnEggItem))));
`

the output should be at the end of the line, I had it at the beginning

**Comment by CrimsonFluff** [comment]
the 'spawns naturally' tooltip has been removed because i will be adding an 'information' tab to REI, like the Forge version of Chickens does in JEI

if and when I ever learn how so to do
