### ISSUE TITLE
More thoughts...

### ISSUE THREAD

**Issue by BernardoGrigiastro** [CrimsonFluff/Crimson-Chickens#23]
Nice to see it back so quick!

1 - I kinda understand you wanting to leave non existent mods chickens enabled but osmium is already available through mythicmetals and if eventually mekanism gets ported the tag i pushed will most prolly work

2 - copper should be vanilla

3 - I guess you cannot remove Rei's plus button before you implement the info tab, right?

4 - how to add custom chickens on fabric? is that working already?

5 - what are your plans for the mod so i can try to help more

6 - do you have a discord? talking through bug reports is a bit weird ;p

**Comment by CrimsonFluff** [comment]
1) ok i'll change osmium
2) I used the same configs as 1.16. originally I changed copper to be minecraft:copper, but I was changing the configs for 1.16 so often, I chose to just overwrite the 1.17 ones.  I usually write 1.16.5 then port to 1.17
3) I barely got REI working at all. I did try to remove the + signs but nothing worked. I also dont like having the spawn eggs as the chicken item.  With JEI you can use the entity itself - this can probably be done in REI but I would have to manually draw the entity, and this requires time and testing
4) On the Forge page click "Pages" top of screen and there is a page for making custom configs - its a bit involved
5) no idea - get it working properly - I also found another client<>server crashing bug - I squashed it before the last beta release.  I would like to add a grinder and maybe someway to produce power?
6) I had a discord but I dont deal with people very well. And being told there werent any configs, or how to get drops, or asked stuff when its all detailed on the CurseForge project page infuriated me so much I deleted the discord channel.  I even had someone tell me it was: "all coding, the worse information they every read, unsub, uninstall, i was a lazy modder and to go fuck myself"

**Comment by BernardoGrigiastro** [comment]
1 - nice
2 - that means you will eventually change it to vanilla? do i remind you here and there or what? :D
3 - yeah i thought so
4 - i saw that page and tried to add a chicken but that data loader mod is not available on fabric AND will stop working on 3rd party launchers soon so thats a no no, anyways... shouldnt the added chicken appear on creative without textures anyways?
5 - i see, nice, adding more modded chickens like "more chickens" mod does is not on the plans? i can help with that i guess
6 - yeah dealing with people is not easy but you've dealing with me just fine :D
7 - one more thing i forgot, there used to be (old mods or smth) a tooltip showing the time left for a baby to grow up which is very nice so we know when to stop feeding seeds as the last x seconds it stops accelerating

**Comment by CrimsonFluff** [comment]
2) We can change it but fabric adds copper to a tag anyways, so job done - plus mod pack makers might unify there ores and just have, for example, mekanism ores (or whatever mod is available)
5) We can add more configs into the mod as we go - but I dont want to add configs for every block in the game - there will always be people that want this block dropped and other people that want that block dropped - we have to draw the line somewhere
7) I didnt add the baby growing timer to waila/jade/one probe for that very reason - other mods do it - I guess I could add it as a config option

**Comment by BernardoGrigiastro** [comment]
2 - cool but i guess no mods will be adding copper anymore, the ones that did are removing it
5 - cool, yeah thats why i mentioned "more chickens" as they are somewhat of a line (i guess) as it was used a lot in the past, anyways... isnt the enabled option there to fulfil dif people needs? 
7 - which one? i'm using wthit+megane and is not showing, maybe i'm being dumb again.... btw you left jade  from forge as an optional dep on cf fabric version instead of wthit
7b - oh i didnt know babies grow on nests, that being a thing it makes sense yes

how about the 4th in my previous comment?

**Comment by CrimsonFluff** [comment]
https://discord.gg/BJNeBAdqWT   keep it private

**Comment by OneLemonyBoi** [comment]
browsing this github and i see this comment appear in real time... 💀

**Comment by CrimsonFluff** [comment]
Always watching  😃

**Comment by BernardoGrigiastro** [comment]
:-D

**Comment by CrimsonFluff** [comment]
conversation has a new home
