### ISSUE TITLE
in game info and translator help

### ISSUE THREAD

**Issue by AlleCraft-alterego** [CrimsonFluff/Crimson-Chickens#24]
I love the great configurability of the various chickens but the whole configuration cannot be seen in game, there is no information, I wanted to understand if the addition of the jei integration is planned (in case you need help you can ask the creator of resourceful bees ) and in any case I can help you translate into Italian if you want, anyway it makes me strange to talk on github, on curseforge there are no other links ....
I met you thanks to "Crimson NBT Tags" I use it often, thanks for that mod !

**Comment by CrimsonFluff** [comment]
so I know fabric has a mod that can show configs in game. I will look into using that

if you would like to translate to Italian, open the jar file using winzip, grab the `assets/crimsonchickens/lang/en-us.json` file and edit it using a text editor

**Comment by AlleCraft-alterego** [comment]
[it_it.zip](https://github.com/CrimsonFluff/Crimson-Chickens/files/7657377/it_it.zip)

**Comment by CrimsonFluff** [comment]
damn that was quick. thank you

**Comment by AlleCraft-alterego** [comment]
how lang was short, compared to the infinite ones I translated long ago
