### ISSUE TITLE
Fabric 1.18 Default chickens won't convert, when fed with item

### ISSUE THREAD

**Issue by DieFetteBrxnette** [CrimsonFluff/Crimson-Chickens#25]
If you feed a Chicken i.e. an iron nugget, there are particles, but it just doesn't do anything else. Even after feeding one stack, it still is a normal chicken, dropping normal eggs.

**Comment by CrimsonFluff** [comment]
I forgot to update the code when I added 'tags' support to the configs

Im working on a fix, thanks

**Comment by CrimsonFluff** [comment]
issue is now fixed, be default its iron_ingots, not nuggets, thought i point that out in case you didnt know  😄
