### ISSUE TITLE
error in jei description (old minecraft lang)

### ISSUE THREAD

**Issue by AlleCraft-alterego** [CrimsonFluff/Crimson-Chickens#26]
in 1.18 biomes lang is changed

https://minecraft.fandom.com/wiki/Java_Edition_1.18#World_generation_2

**Comment by CrimsonFluff** [comment]
Im sure I changed the biomes for 1.18, maybe I only did the fabric version? I'll check it

**Comment by CrimsonFluff** [comment]
fixed. now same as fabric version
