### ISSUE TITLE
pls release 1.17 on curseforge

### ISSUE THREAD

**Issue by guest256** [CrimsonFluff/Crimson-Chickens#27]

**Comment by guest256** [comment]
no need if you dont feel like it

**Comment by CrimsonFluff** [comment]
I did support 1.17.1 for a short time
But my mod count is growing and Im finding it hard to maintain them all - therefore I decided not to continue support for 1.17 - Also I feel that most players will either stay with 1.16.5 or move on to 1.18

😄
