### ISSUE TITLE
Don't understand breeding

### ISSUE THREAD

**Issue by Theonlyoxymel** [CrimsonFluff/Crimson-Chickens#29]
How do I breed the chickens

**Comment by CrimsonFluff** [comment]
Here is the unofficial official wiki on breeding chickens - its about half way down
https://minecraft.fandom.com/wiki/Chicken

Use JEI/REI to tell you which chickens breed together
Here are some pictures: https://www.curseforge.com/minecraft/mc-mods/crimson-chickens/screenshots

For example: find a log chicken and a flint chicken, feed them both seeds, like in vanilla, and they have a chance to produce coal chicken babies

**Comment by CrimsonFluff** [comment]
so there seems to be a problem with Fabric breeding of chickens....

**Comment by CrimsonFluff** [comment]
change the `MasterSwitchBreeding in the `config/crimsonchickens.json` file from `0` to `2`
