### ISSUE TITLE
forge?

### ISSUE THREAD

**Issue by MercilessArchitect** [CrimsonFluff/Crimson-Chickens#32]
i know this mod had a forge working port at some point for 1.18. i had it on my pack and it loaded just fine. why did you remove it?

**Comment by CrimsonFluff** [comment]
It had a bug in it that could corrupt tile entities.  I only noticed it by chance as it didn't happen in the Dev. I didn't want to distribute a broken mod so I pulled it

I've hopefully fixed it, and it will be released soon

**Comment by CrimsonFluff** [comment]
new version of CurseForge
