### ISSUE TITLE
Update for 1.18 as well?

### ISSUE THREAD

**Issue by DieFetteBrxnette** [CrimsonFluff/Crimson-Chickens#34]
Hey it's me again!
I love this mod, but I'm using a modpack for version 1.18. and it doesn't work with the 1.18.1 version of the mod.
Would you be able to make crimson chickens 1.0.2 available for 1.18 as well? 

However, great mod even, if it's the wrong version for me personally. :)

**Comment by CrimsonFluff** [comment]
I'm gonna say no

Its not hard for mods to update from 1.18 to 1.18.1.  And I believe the world is already going backwards what with Flat Earthers and Anti Vaxxers. So lets start a trend - and move forward !

😃
