### ISSUE TITLE
Chickens spawning underground

### ISSUE THREAD

**Issue by PurpleHel** [CrimsonFluff/Crimson-Chickens#35]
I keep having chickens and ducks spawn underground, and then I feel bad and have to go rescue them. It'd be nice if there was a config option to make mobs from this mod only spawn above ground, either via Y check or more complicated ones. (Can you have things only spawn if there's a clear view of the sky or something similar?)
1.16.5

**Comment by CrimsonFluff** [comment]
I know the chickens annoyingly spawn in lava in the Nether, but never noticed a problem in the Overworld - but then I didn't do a lot of cave work

I probably got the spawn code wrong.  I was thinking of adding options to the configs to set `spawnableBlocks`. So soul sand chickens only spawn on soul sand, ducks can spawn on grass and dirt etc

**Comment by CrimsonFluff** [comment]
Also you seem vaguely familiar?  are you on YT or Twitch?

**Comment by PurpleHel** [comment]
I used to have a twitch stream with a friend, but I am not especially active on YT or twitch now. I do comment on mods a good bit tho, especially to suggest things. :) I *am* or twitter and tumblr and such too.

**Comment by CrimsonFluff** [comment]
So atm 1.16.5 of chickens is way behind on updates and I can't access Curseforge due to `internal error`

But I promise to try and re-work the spawning  😸

**Comment by PurpleHel** [comment]
It's all good, I certainly don't expect instant fixes! I was just like 'huh, this is minorly bugging me, lemme go say something'. :)

**Comment by CrimsonFluff** [comment]
Hello.  Merry after xmas,

I have a test version of the chickens for 1.16.5 if you would be so kind to test for me
You don't have to, so don't feel pressured  😄 

I've made a change to spawning and have noticed that the chickens don't spawn so much in lava now in the Nether. As for Overworld caves I havn't really looked at

It would be best to start a new world and delete the config/crimsonchickens folder as I made some config changes that I seem to have missed some stuff from

heres the mod, from my onedrive: https://1drv.ms/u/s!ArSGAcC04KWsyw7wDNaSmdMC6hoo?e=VJdlEA

**Comment by PurpleHel** [comment]
I'll give it a shot tonight, but I won't have a lot of time this week to game-We have to work extra hours all week to get everything done cos we have friday off. I'll report back what I see tho!

**Comment by CrimsonFluff** [comment]
spawns now based on config block and config light levels, so should fix this

unless theres enough light underground and the correct block to spawn on
