### ISSUE TITLE
Server crashes when breeding

### ISSUE THREAD

**Issue by TheButterbrotMan** [CrimsonFluff/Crimson-Chickens#36]
Hello, my Server is crashing when breeding them.

https://pastebin.com/sucWQ92b

**Comment by TheButterbrotMan** [comment]
Probably linked to #28

**Comment by wackoamd1** [comment]
thats just a ticking entity kill the bugger from console and get it over with , although i dont think its strange with that amount of mods ;-)

**Comment by CrimsonFluff** [comment]
I cant actually track the error despite it giving me the line that caused it because Ive overwritten the code with the next update

I currently have an error im trying to track but should release an alpha if anyone could try that for me?

**Comment by CrimsonFluff** [comment]
heres an alpha   Fabric 1.18.1
https://1drv.ms/u/s!ArSGAcC04KWsyw_ZOtdmGzRoWbeK?e=8wiawr

**Comment by TheButterbrotMan** [comment]
Another crash linked to this:

https://pastebin.com/j6dTjgBE

**Comment by TheButterbrotMan** [comment]
> 

What exactly you want me to test?

**Comment by CrimsonFluff** [comment]
do what ever you did to make it crash last time?  Because I changed the code I cant track the error, so if anything I need a fresh crash log

**Comment by TheButterbrotMan** [comment]
Ok will try.

**Comment by TheButterbrotMan** [comment]
Please upload the file again, can try it now.

**Comment by CrimsonFluff** [comment]
suspected mod incompatibility with Not Enough Breeding
