### ISSUE TITLE
Custom chicken don't have egg texture

### ISSUE THREAD

**Issue by AlleCraft-alterego** [CrimsonFluff/Crimson-Chickens#38]
Minecraft : 1.18.1
Forge : 39.0.8
Crimson Chickens : 1.0.1

custom chicken don't have egg texture

![2021-12-29_06 48 25](https://user-images.githubusercontent.com/72225590/147631254-58762c85-30d7-472d-86d9-f48f959a0d27.png)
[inert_crystal.zip](https://github.com/CrimsonFluff/Crimson-Chickens/files/7787505/inert_crystal.zip)

**Comment by CrimsonFluff** [comment]
did you give them textures?

https://www.curseforge.com/minecraft/mc-mods/crimson-chickens/pages/creating-a-custom-chicken

**Comment by AlleCraft-alterego** [comment]
mh... i have add custom cicken on "modded" folder on config, and i thinking color option in custom file made the egg

**Comment by AlleCraft-alterego** [comment]
I couldn't find the wiki on github and thought I hadn't done it yet

**Comment by CrimsonFluff** [comment]
atm you need to supply the textures in a resource pack, and have a 3rd party mod load that resource pack, like https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by AlleCraft-alterego** [comment]
I did it with chicken, but not for the egg.
for the egg what should I put to use the colors I put in the config?

**Comment by CrimsonFluff** [comment]
you need to add a spawn egg model json file for every egg you add

look inside the jar file in assets/models/item  there is a json for every spawn egg type

**Comment by CrimsonFluff** [comment]
I've done some experimenting and the resource pack reloading/spawn egg texture problem seems to be fixed?

So you don't need to add `spawn_egg.json` files

so heres a test version for you - Forge 1.18.1 - https://1drv.ms/u/s!ArSGAcC04KWsyxBjJS6umtWT2qFp?e=doU64S

**Comment by AlleCraft-alterego** [comment]
thanks, work !
but why don't you use the hexadecimal system? it's what I've always seen used in mods...

**Comment by CrimsonFluff** [comment]
Because when I wrote the configs I didnt know anything about jsons or serializers in code
or how to read/write jsons using code
the configs would have to store the Hex as a String, then process into an Int number anyways - so I kept it simple

and lets face it, not many people will create their own custom chickens - and I did give links to online resources people can use

**Comment by AlleCraft-alterego** [comment]
the only thing I recommend is to move or copy the wiki to github

**Comment by CrimsonFluff** [comment]
more work for me, yay

**Comment by AlleCraft-alterego** [comment]
yes
