### ISSUE TITLE
no texture on chicken

### ISSUE THREAD

**Issue by wackoamd1** [CrimsonFluff/Crimson-Chickens#39]
crimson i really need your help before i go insane

i made a custom egg , put the json in a "custom" folder besides modded and vanilla folders in de config.
the egg is working the chicken is working , but i cant get the texture to work .

im using openloader and the texture pack gets loaded but i still have a pink and black chicken ;-(
.minecraft\config\openloader\resources\crimsoncustomchickens\assets\crimsonchickens\textures\entity\*same as chicken*.png
wth is wrong , its just a standard recolored chicken file
![netherstar](https://user-images.githubusercontent.com/5446360/147895401-8940ede7-606a-4629-8d87-018e8376ac5f.png)

**Comment by CrimsonFluff** [comment]
did not fill in bug report
![2022-01-03_04 05 33](https://user-images.githubusercontent.com/10263667/147898990-7a189bb8-eba4-4283-ae42-b20316d6f62e.png)

**Comment by wackoamd1** [comment]
what are u using to load them , cause the global data and resourcepacks u link to in the custom chicken pages is for forge and not fabric.
