### ISSUE TITLE
crash while exploring . 

### ISSUE THREAD

**Issue by TheRanker** [CrimsonFluff/Crimson-Chickens#40]
Without this basic information your issue will be deleted...

**Basic Mod Information**
Forge Version
Fabric Version 0.12.12
Mod Version Crimson Chickens 1.18.1-Fabric-v1.0.2
Server, Client or Both

**Describe the bug**
What is the bug? What did you do to make it happen? is it repeatable? 

explore the world. crashes to desktop ... multiple crashes, same crash report. 
error in log 
: Failed to temporary create Optional[ResourceKey[minecraft:entity_type / crimsonchickens:angry]] mob in order to check if it is an arthropod that bees should be naturally angry at. Will check if mob is a bear or wasp in its name instead. Error message is: Cannot read field "displayName" because "this.chickenData" is null
[19:13:58] [Server thread/WARN]: Failed to temporary create Optional[ResourceKey[minecraft:entity_type / crimsonchickens:blaze]] mob in order to check if it is an arthropod that bees should be naturally angry at. Will check if mob is a bear or wasp in its name instead. Error message is: Cannot read field "displayName" because "this.chickenData" is null

goes on for almost all the chicken types.

ive deleted the configs and mod and re added. same result.

this may be a mod conflict as this never happened before and the mod wasnt updated in some time. 
but some direction is needed for me to start resolving the issues. hopeing you can assist :)

**Crash Log**
https://pastebin.ubuntu.com/p/wWMG5q4jb6/

**Comment by CrimsonFluff** [comment]
it is indeed a mod conflict as I dont check for bees/bears/wasps or whatevers

please try this latest dev version: https://1drv.ms/u/s!ArSGAcC04KWsyxOk8ks7_w6uwvJU?e=x8Uwxd

**Comment by CrimsonFluff** [comment]
cool, i'll release it soon

**Comment by arquxx** [comment]
it's sad to see you've removed 1.18 fabric version, what happened?

**Comment by TheRanker** [comment]
Added the latest release. No issues  :) Ty for ur help
