### ISSUE TITLE
nest are no  "inventory"

### ISSUE THREAD

**Issue by wackoamd1** [CrimsonFluff/Crimson-Chickens#41]
Without this basic information your issue will be deleted...

**Basic Mod Information**

Fabric Version1.12.2
Mod Version 1.02
Both

**Describe the bug**
the nest are not recognized as inventory  , i cant hook up any form of automation to insert seeds which sucks with more then 65 chickens ;-(
also why are the seeds besides the chicken and not like before "IN" the nest so wthit shows them , which it doesnt now.

i love the chickens but this really sucks and kinda makes the chickens useless , only able to feed them by hand which i allready did to level them up.

by the time i fed all the chickens i can go back to the first one because u cant hold 65 stack seeds so u have to run to  your chest to get seeds ;-(

edit:
lol after some testing i cant even manual get the stuff from the nest it NEEDS a chest not even a storage system works for taking stuff out of the nest.

**Comment by CrimsonFluff** [comment]
seems the inventory has messed up  - this is a bug - it was not done on purpose - so calm down

**Comment by wackoamd1** [comment]
hahaha im calm ;-) happy its a bug , i love your mods ;-)

**Comment by wackoamd1** [comment]
thanks for the fast update ;-) works fine now.
just 1 question which i hopefully can fix myself.
why do i get 3 logs every 9 minutes and diamonds , netherite etc... every 45seconds or so?

**Comment by CrimsonFluff** [comment]
I would imagine you have 10/10/10 diamond/netherite chickens and 1/1/1 log chickens?

FYI: Havn't worked out how to get WAILA to show the nest inventory but I plan on adding this feature

**Comment by wackoamd1** [comment]
uhm nope they are all 10/10/10 thats what is so weird

**Comment by CrimsonFluff** [comment]
can you capture the chickens in nets, put the nets in ya inventory and send me your `saves/world/level.dat` file so I can check the nbt data

**Comment by wackoamd1** [comment]
i bred it again , and now its fine , probably just a glitched chicken ;-)
