### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1856.method_8105()" because "ingredient" is null

### ISSUE THREAD

**Issue by TheButterbrotMan** [CrimsonFluff/Crimson-Chickens#44]
Basic Mod Information
Fabric: 0.12.12
v1.0.4
Server

**Describe the bug**
Is crashing randomly

**Crash Log**
https://pastebin.com/1Wz2sTY8

**Comment by CrimsonFluff** [comment]
what were you doing to cause the error?  is it repeatable?

**Comment by CrimsonFluff** [comment]
try this for a while - Ive disabled the A.I overrides - you will NOT get any drops in world - like when a chicken usuallydrops an egg in world, this shouldnt happen

https://1drv.ms/u/s!ArSGAcC04KWsyxU0cDzg5oB6s80E?e=KiBliH

**Comment by CrimsonFluff** [comment]
FYI - I wasnt being rude with your issue, I just need more info to go on... like version of the mod as Forge and Fabric are different and what you were doing to cause the error - exploring? breeding? Nest related issues?  etc

**Comment by TheButterbrotMan** [comment]
> what were you doing to cause the error? is it repeatable?
> I dont know. Just crashed multiple times a day.
> it seems its to do with vanilla A.I. so prob not much I can do
> 
> I'll post an update for you to try, but after that im at a loss

**Comment by TheButterbrotMan** [comment]
Could be there any mod causing this? If you could tell me the type, i had maybe an idea.

**Comment by CrimsonFluff** [comment]
all I know is its something AI related - I need help in tracking the error - it mentions `tempt_goal`  which is called when feeding entities, like when you hold seeds and chickens follow you

**Comment by TheButterbrotMan** [comment]
1. Some player told me that all ender chickens, coming trough the portal in the overworld, i cant verify if its the reason.

**Comment by CrimsonFluff** [comment]
were they being lead thru the portal?  like someone holding seeds and they walk thru?

**Comment by TheButterbrotMan** [comment]
The portal is open, after the dragon is killed, and the randomly running in.

**Comment by TheButterbrotMan** [comment]
Nobody is holding seed

**Comment by CrimsonFluff** [comment]
if you could get everyone to use that version of the mod I just posted, and update the server, see if that works

**Comment by TheButterbrotMan** [comment]
It seems to work, but i cant verify its fixing the issue, because i dont know how to reproduce it.

I also have this chicken related mods:
https://www.curseforge.com/minecraft/mc-mods/despawning-eggs-hatch-fabric
https://www.curseforge.com/minecraft/mc-mods/chickensshed

**Comment by CrimsonFluff** [comment]
I just forced some ender chickens thru the end portal, all seems fine

the `Despawning Eggs` shouldn't affect ender chickens as they don't drop eggs - only vanilla chickens (by vanilla i mean the plain white chickens) drop eggs in world
and `Chicken Shed` should only be when shearing the chickens

**Comment by TheButterbrotMan** [comment]
Give me some minutes i try to reproduce it somehow.

**Comment by TheButterbrotMan** [comment]
When you breed them it crashs.

**Comment by TheButterbrotMan** [comment]
I will provide an new crashlog

**Comment by CrimsonFluff** [comment]
are there any auto-feeding charms? or machines that auto feed running?  if we can try any things that could cause a `temptation goal` to happen

**Comment by CrimsonFluff** [comment]
can you zip me your modpack so I can try

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment]
We have this also: https://www.curseforge.com/minecraft/mc-mods/animal-feeding-trough

But it shouldnt be spawning naturally, additional nobody is using it.

**Comment by CrimsonFluff** [comment]
so you are feeding enderman chickens?  what are you feeding with? and does it happen to other crimson chickens types?

**Comment by TheButterbrotMan** [comment]
> so you are feeding enderman chickens? what are you feeding with? and does it happen to other crimson chickens types?
> Seeds, i dont know -> will test
> also was the latest crashes with the file I linked to you a few minutes ago?
> Waiting for the result -> In Testing

**Comment by CrimsonFluff** [comment]
524 mods?  thats waaaaaaaaaaaaaaaaaaaaaaay too many

**Comment by TheButterbrotMan** [comment]
It runs pretty good :D

**Comment by CrimsonFluff** [comment]
and im supposed to debug this?

**Comment by CrimsonFluff** [comment]
id imagine it is good on a xeon !

**Comment by TheButterbrotMan** [comment]
"also was the latest crashes with the file I linked to you a few minutes ago?"

No

**Comment by TheButterbrotMan** [comment]
I will have another crashlog, with new file soon (If it crashs)

**Comment by TheButterbrotMan** [comment]
Could be linked to #36

**Comment by CrimsonFluff** [comment]
would it be possible to try with crimson chickens mod?  see if it happens to regular vanilla chickens?  does it happen in single player?

**Comment by TheButterbrotMan** [comment]
> would it be possible to try with crimson chickens mod? see if it happens to regular vanilla chickens? does it happen in single player?

Does happen in Singleplayer also. 

I will soon have the results for the fixed file.

**Comment by CrimsonFluff** [comment]
thats 400+ mods for issue #36

**Comment by CrimsonFluff** [comment]
I meant **without** the crimson chickens mod to see if vanilla chickens have the same issue

**Comment by TheButterbrotMan** [comment]
I will try it.

**Comment by TheButterbrotMan** [comment]
> 

No.

**Comment by TheButterbrotMan** [comment]
> I meant **without** the crimson chickens mod to see if vanilla chickens have the same issue

No.

**Comment by CrimsonFluff** [comment]
have a new one for testing - ive removed the breeding item override - see if thats the cause

https://1drv.ms/u/s!ArSGAcC04KWsyxU0cDzg5oB6s80E?e=ifCppu

also your modpack is taking a million years to install

**Comment by TheButterbrotMan** [comment]
Absolutly, i told it. Installing is a pain. Sadly GDLauncher cant acces cf api properly.

**Comment by TheButterbrotMan** [comment]
Sooo, i finally tested with your Mod without, without both version.

If i use the newest version, i am unable to breed them (All starts lagging if i try)
If i uninstall the mod i am unable to breed chickens. 

Probably has to be some mod, = no problem with your mod. 

Sorry for your stealed time, thank you for this awesome mod!

**Comment by TheButterbrotMan** [comment]
I use your other Crimson mods also, they are working fine!

**Comment by CrimsonFluff** [comment]
hey all is good - I saw you use the slimes and goats mods - I love the goats mod  😸 

if you do narrow down the problem mod, just let me know - im gonna do some testing if your pack ever installs - stoopid curseforge !

**Comment by TheButterbrotMan** [comment]
Try GDLauncher sometimes it works

**Comment by CrimsonFluff** [comment]
forgot to say that chickens has a config to allow shearing - so could save a mod there !  lolz

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/not-enough-breeding found the reason

**Comment by TheButterbrotMan** [comment]
Your mod works now!

**Comment by CrimsonFluff** [comment]
well indeed.  I was going to make a similar mod, lol

thank you for your help !  😺

**Comment by CrimsonFluff** [comment]
remember to re-download the chickens mod - cos the versions I posted here are technically broken cos I disabled some stuff trying to debug them  :-)

**Comment by TheButterbrotMan** [comment]
Probably some mod that enhaces livestock entirely would be awesome

**Comment by TheButterbrotMan** [comment]
> remember to re-download the chickens mod - cos the versions I posted here are technically broken cos I disabled some stuff trying to debug them :-)

Already did
