### ISSUE TITLE
Can't spawn chicken

### ISSUE THREAD

**Issue by InfernumYT** [CrimsonFluff/Crimson-Chickens#46]
Can't spawn chicken using chicken spawn egg, and spawn eggs from mod is missing(1.0.2v of mod is fine)
Forge: 1.18.1-39.0.79

**Comment by CrimsonFluff** [comment]
did you delete the 'config/crimsonchickens' folder as the configs have changed?  because they appear in mine

**Comment by InfernumYT** [comment]
ok now it work's
