### ISSUE TITLE
Random crash on a fresh world.

### ISSUE THREAD

**Issue by frikinjay** [CrimsonFluff/Crimson-Chickens#47]
Without this basic information your issue will be deleted...

**Basic Mod Information**
Forge Version
Fabric Version : 0.13.2
Mod Version : 1.0.5
Server, Client or Both : server

**Describe the bug**
What is the bug? What did you do to make it happen? is it repeatable? 
Just roamed around on a fresh world

**Crash Log**
Paste the crash.log/latest.log to PasteBin.com (its free) and paste that link here
https://pastebin.com/aSFQmqmV

**Comment by CrimsonFluff** [comment]
you running extra mods, like Carpet for instance?

**Comment by frikinjay** [comment]
The configs are fresh and yes i am running the mod alongside other mods.

**Comment by CrimsonFluff** [comment]
try this, if it happens again can you supply the new crash and latest logs please

https://1drv.ms/u/s!ArSGAcC04KWsyxv2ls3RWFbWiWj8?e=y6c4ry

**Comment by frikinjay** [comment]
I deleted the old configs completely. Looks like the directory needs to be deleted for the configs to gen again. Seem to be working fine for now. If it happens again i will try the above. Thanks.

**Comment by CrimsonFluff** [comment]
Hopefully thats the last time I need to change the configs - its worth checking the changelog on the mod download page as I do mention world breaking/config changes - harder to do if you're playing a modpack, but always worth a check  :-)

**Comment by frikinjay** [comment]
Yeah I usually do check changelogs just one or two mods slip through at times.
