### ISSUE TITLE
NullPointerException: Cannot read field "entityType" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by TheButterbrotMan** [CrimsonFluff/Crimson-Chickens#48]
Without this basic information your issue will be deleted...

**Basic Mod Information**
Fabric Version: 0.13.3
Mod Version:1.0.5
Both

**Describe the bug**
Wandering around.

**Crash Log**
https://crashy.net/c2cqjBaaZqNbUgJU4PYi

**Comment by CrimsonFluff** [comment]
did you delete your config/crimsonchickens folder ?
