### ISSUE TITLE
1.18.2  Chickens not laying

### ISSUE THREAD

**Issue by Chunkimunki** [CrimsonFluff/Crimson-Chickens#53]
Forge Version : 40.0.32
Mod Version : 1.0.0
 Client 

**Describe the bug**
Chickens both regular and modded not laying eggs/drops.
Checked chickens in vanilla - forge no mods - forge with just this mod and Jade.
Only this mod seemingly stops the drops.
Jade shows the 'time to next egg' timer frozen.

If you need logs let me know.  Cheers

**Comment by CrimsonFluff** [comment]
the chickens configs are defaulted to NOT drop eggs in the world

if they drop items in world, then why bother with a nest?  check your `crimsonchickens-common.toml` config file

**Comment by Chunkimunki** [comment]
oops - so sorry to bother. Played earlier versions of your most excellent mod where drops were all over the place. Makes total sense to have to use the nest.  Damn should open m'eyes a bit. Thanks though for the reply-cheers

**Comment by CrimsonFluff** [comment]
All good dude  😸
