### ISSUE TITLE
How do you get lava chickens?

### ISSUE THREAD

**Issue by GhostFire90** [CrimsonFluff/Crimson-Chickens#9]
Seeing as there isnt really a wiki on this, how do you get lava chickens? is there a breeding thing that isnt showing up in nei?

**Comment by CrimsonFluff** [comment]
you'll need to change the config for lava chickens/water chickens and give them parents or biomes to spawn in

guess I missed them out when testing

**Comment by CrimsonFluff** [comment]
offered temp fix
fixed in next update
